config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  resources :users, only: [:show]
  root to: 'home#index'

  match 'jobs/:id/edit', to: 'jobs#edit', via: [:patch]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  enum response: { no_response: 0, refused:1, interview:2, accepted:3}

  enum interview_stage: { no_interview:0, phone_interview:1, first_face_interview:2, second_face_interview:3, concluded:4
    }

  validates :company, :role, :application_date,presence: true

  belongs_to :user

  ##for the paginate gem
  self.per_page = 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  validates :email, presence: true, on: [:create, :update]
  validates :username, presence: true
  validates_uniqueness_of :username, :email

  devise :database_authenticatable, authentication_keys: [:username]

  has_many :jobs

  # jobs with  response
  def response_jobs
    jobs.where.not(response: 'no_response').count
  end

  # jobs refused
  def refused_jobs
    jobs.where(response: 'refused').count
  end

  # jobswith interview
  def interview_jobs
    jobs.where(response: 'interview').count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    jobs_path
  end

  ## add a username to the devise paramters
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:username, :email])
  end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  respond_to :html, :js, :json

  before_action :authenticate_user!

  def index
    @my_job = Job.where(user_id: current_user.id)
    @q = @my_job.ransack(params[:q])
    @jobs = @q.result.paginate(page: params[:page]).order(pin: :desc, created_at: :desc)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new job_params
    if @job.save
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find params[:id]
  end

  def update
    @job = Job.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
    render index if @job.update_attributes(job_params)
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to action: :index, status: 303 
  end

  ## used to change the pin value

  private

  # unless the user selects interview stage we automatically set the interview stage so it wont display

  def job_params
    params.require(:job).permit(:company, :role, :salary, :application_date, :application_closing_date, :contact_name, :contact_email, :contact_phone, :description, :link, :response, :interview_stage, :notes, :pin, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
#homepage
  #overlay
    .row#home-container
      #left.col.s12.l8
        h1 MyApplicationMate
        h3 To help you organize your job applications
        h4 Try it now for free
      #right.col.s12.l4
        = link_to "Register now", new_user_registration_path, class:'btn btn-large main-bg-color'
        = link_to "Log In", new_user_session_path, class:'btn btn-large'

app/views/jobs/_card.html.slim
.row#job-card
  .card
    .pin-form
      = render partial: 'jobs/pin_icon', locals: {job:job}
    .row.destroy
      /!job is defined in job index.htmlslim
      = link_to "x", job, method: :delete,class:'btn-floating.waves-effect.waves-light', data: {confirm: "Are you sure you want to delete the record?"}
    .card-content
      .card-title
        .row
          .col.s12.l6
              b = job.role
              |  at 
              b = job.company
          .col.s12.l6.form-response
              = render partial: 'jobs/select_response', locals: {job:job}

              
      p 
        = job.application_date.strftime("Applied on %d/%m/%Y ")
        - if Time.now > job.application_closing_date 
          b = job.application_closing_date.strftime("|| Closed on %d/%m/%Y")
        - else
          b = job.application_closing_date.strftime("|| Closing on %d/%m/%Y")
          //icon to collapse the description
      a.btn-floating.halfway-fab.waves-effect.waves-light.collapse-icon
        i.material-icons.icon-collapse add
        
        
    // by default hide it to make the card more compact    
    .card-tabs.hide
      ul.tabs.tabs-fixed-width
        li.tab
          // link the tab with the divs below
          a[href="#test#{job.id.to_s}#{'a'}"]
            | Description
        li.tab
          a[href="#test#{job.id.to_s}#{'b'}"]
            | Contacts
        li.tab
          a[href="#test#{job.id.to_s}#{'c'}"]
            | Notes
    // by default hide it to make the card more compact   
    .card-content.card-description.hide

      div[id="test#{job.id.to_s}#{'a'}"]
        p 
          b Link: 
          = job.link       
        br
          b Salary: 
          = job.salary 
        br
          b Description: 
          = job.description

      div[id="test#{job.id.to_s}#{'b'}"]
        = job.contact_name
        br 
        = job.contact_email
        br
        = job.contact_phone

      div[id="test#{job.id.to_s}#{'c'}"]
        // if you rename the class remember to change in the jobs.js
      

        
        a.btn-floating.main-bg-color.note-edit.right-align
          i.material-icons mode_edit
        br
        = form_for job, url: job_path(job), remote: true,method: :patch do |jj|
          = jj.hidden_field :id
          = jj.label :notes
          = jj.text_area :notes, :readonly => true
          = jj.submit "Update", class:'hide btn secondary-bg-color'

app/views/jobs/_form.html.slim
.container
  h1 Add a new job application
  .row#create-form
    = form_for @job do |f|
      - if @job.errors.any?
        #error_explanation
          h2 
          = pluralize(@job.errors.count, "error")
          |  prohibited this job to beng saved:
          ul
            - @job.errors.full_messages.each do |message|
              li = message
      = f.hidden_field :user_id, :value => current_user.id
      .input_field.col.s12
        = f.label :company
        = f.text_field :company
      .input_field.col.s12
        = f.label :role
        = f.text_field :role
      .input_field.col.s12.l6
        = f.label :link
        = f.text_field :link
      .input_field.col.s12.l6
        = f.label :salary
        = f.number_field :salary
      .row
        .input_field.col.s12.l6
          = f.label :application_date
          = f.date_field :application_date, class:'datepicker'
        .input_field.col.s12.l6
          = f.label :application_closing_date
          = f.date_field :application_closing_date, class:'datepicker'
      .input_field
        = f.label :description
        = f.text_area :description
      h2 Contacts
      .row
        .input_field.col.s12.l4
          = f.label :contact_name
          = f.text_field :contact_name
        .input_field.col.s12.l4
          = f.label :contact_email
          = f.email_field :contact_email
        .input_field.col.s12.l4
          = f.label :contact_phone
          = f.phone_field :contact_phone
        .input_field
          = f.submit "Create", class:'btn btn-large waves-effect waves-light main-bg-color'

app/views/jobs/_pin_icon.html.slim
= form_for job, url: job_path(job), method: :put, remote: true do |pin|
    - if job.pin === false
        = pin.hidden_field :pin, :value => 'true'
        = button_tag type: 'submit', class: 'btn btn-floating pin-icon secondary-bg-color' do
          i.material-icons label_outline
    - else
        = pin.hidden_field :pin, :value => 'false'
        = button_tag type: 'submit', class: 'btn btn-floating pin-icon main-bg-color' do
          i.material-icons label_outline

app/views/jobs/_search_form.html.slim
.row#search-forms
  .col.s12.l4
    = search_form_for @q do |f|
      = f.label :company_or_role_or_description_cont, "Search for company or role"
      = f.search_field :company_or_role_or_description_cont
      = f.submit "Search", class:'btn secondary-bg-color'
  .col.s12.l4
    = search_form_for @q do |f|
      = f.label :response
      = f.select :response_eq, Job.responses.to_a.map { |w| [w  [0].humanize, w[1]]}, {:include_blank => true}
      = f.submit  class:'btn secondary-bg-color'
  .col.s12.l4
    = search_form_for @q do |f|
      = f.label :interview_stage
      = f.select :interview_stage_eq, Job.interview_stages.to_a.map { |w| [w[0].humanize, w[1]]}, {:include_blank => true}
      = f.submit  class:'btn secondary-bg-color'

app/views/jobs/_select_response.html.slim
= form_for job, url: job_path(job),remote: true,method: :put do |jj|
  = jj.select :response, Job.responses.keys
  - if job.response === 'interview'
    = jj.select :interview_stage, Job.interview_stages.keys
  = jj.submit "Update", class:'secondary-bg-color btn btn-response'

app/views/jobs/edit.html.slim
h1 Edit me 
= @job.role
= @job.notes

app/views/jobs/index.html.slim
.container
  // btn to add new job
  .fixed-action-btn
    .btn-floating.btn-large.main-bg-color.new-icon
      a href='/jobs/new'
        i.material-icons add
  br
  br
  br
  .card
    .card-content
      h2 Search and Filter
      = render 'jobs/search_form'
  // create ransack form for responses and interviews
  br
  br
  br
  .row
    .col.12
      .btn.new-job-button.main-bg-color
        = link_to "Add a new job appication",new_job_path, class:'main-font-color'

  #my-jobs
    h1 Your job applications
    br
    br
    - @jobs.each do |j|
      .job-cards
        = render partial: 'jobs/card', locals: {job:j}

        // implement infinite scrolling here
    
    = will_paginate @jobs

app/views/jobs/new.html.slim
= render 'jobs/form'

app/views/layouts/_footer.html.slim
footer.main-bg-color
  .container.page-footer.main-bg-color
    .row
      .col.l6.s12
        h5 Job Aplication Mate
        p.text-lighten-4 
      .col.l4.offset-l2.s12
        h5 
        ul
        - if user_signed_in?
          li 
            = link_to "Log Out", destroy_user_session_path, method: :delete
          li
            = link_to "My Profile", user_path(current_user)
          li
            = link_to "My Jobs", jobs_path
        - else
          li
            = link_to "Register", new_user_registration_path
          li
            = link_to "Log In", new_user_session_path
  .footer-copyright.main-bg-color-dark
    .container.page-footer.main-bg-color-dark
      | © 2017 Copyright Alberto Montalesi
      a.right href="https://github.com/AlbertoMontalesi/JobApplicationTracker"  Contribute on Github

app/views/layouts/_navbar.html.slim
nav.main-bg-color
  .nav-wrapper
    = link_to "My Application Mate", jobs_path, class:"brand-logo"
    a.button-collapse data-activates="mobile-demo" href="#" 
      i.material-icons menu
    ul.right.hide-on-med-and-down
      - if user_signed_in?
        li 
          = link_to "Log Out", destroy_user_session_path, method: :delete
        li
          = link_to "My Profile", user_path(current_user)
        li
          = link_to "My Jobs", jobs_path
      - else
        li
          = link_to "Register", new_user_registration_path
        li
          = link_to "Log In", new_user_session_path
    ul#mobile-demo.side-nav
      - if user_signed_in?
        li 
          = link_to "Log Out", destroy_user_session_path, method: :delete
        li
          = link_to "My Profile", user_path(current_user)
        li
          = link_to "My Jobs", jobs_path
      - else
        li
          = link_to "Register", new_user_registration_path
        li
          = link_to "Log In", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title JobTasker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="/assets/javascripts/manifest.json" rel="manifest" /
    meta content="#262626" name="theme-color" /
    meta content="yes" name="apple-mobile-web-app-capable" /
    meta content="default" name="apple-mobile-web-app-status-bar-style" /
    meta content="JobMate" name="apple-mobile-web-app-title" /
    link href="/app/assets/images/icons/icon-32.png" rel="apple-touch-icon" sizes="32x32" /
    link href="/app/assets/images/icons/icon-64.png" rel="apple-touch-icon" sizes="64x64" /
    link href="/app/assets/images/icons/icon-128.png" rel="apple-touch-icon" sizes="128x128" /
    link href="/app/assets/images/icons/icon-256.png" rel="apple-touch-icon" sizes="256x256" /
    link href="/app/assets/images/icons/icon-512.png" rel="apple-touch-icon" sizes="512x512" /
    = favicon_link_tag 'favicon.png'
  
  body
    main
      = render 'layouts/navbar'
      / .notice= notice
      / .alert= alert
      = yield
    = render 'layouts/footer' unless(params[:controller] === "home" && params[:action] === "index")


   

app/views/users/show.html.slim
.container#user-profile
  .row
    .col.s12
      h1 = @user.username
  .row
    .col.s12.l4
      .card
        .card-title
          = @user.jobs.count
        .card-description
          p Jobs added
    .col.s12.l4
      .card
        .card-title
          = @user.response_jobs
        .card-description
          p Responses
    .col.s12.l4
      .card
        .card-title
          = @user.refused_jobs
        .card-description
          p Refusal
  .row
    .col-s12
      ul
        li
          = link_to "Edit Profile", edit_user_registration_path(current_user)
        



  / h1 Hello #{@user.email}

  / h2 Your applications
  / .row
  /   .col.s12.m4
  /     /* display total jobs applied */
  /     p You applied #{@user.jobs.count} Jobs
  /   .col.s12.m4
  /     // display jobs where the user received a response
  /     p You received #{@user.jobs.where.not(response: 'no_response').count} responses